# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google Maps API Key (Copy from dev or add here)
# google.api.key=YOUR_API_KEY
spring.mail.username=ayushmanpal845@gmail.com
spring.mail.password=cxgx drsw cmhh owwo

google.client.id=379565691907-9mtgjgc6qtvrliq95a0quu0nii5au0kn.apps.googleusercontent.com

logging.level.root=info

#MQTT config
mqtt.broker.url=ssl://s18a2a01.ala.asia-southeast1.emqxsl.com
mqtt.client.id=springBootClient
mqtt.username=EcoMonitor
mqtt.password=JTjb!4SWV@Tx@A7

google.api.key=AIzaSyCieMp7PMEqhy_HJQbr34lTUWlcEqd7wpc
