# Database config

spring.datasource.url=jdbc:postgresql://postgres:IZNhfSkFTtLIYDJPeDnQUwygrWJaSDBi@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=IZNhfSkFTtLIYDJPeDnQUwygrWJaSDBi

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
# Email config
spring.mail.username=ayushmanpal845@gmail.com
spring.mail.password=zlie lteu dppb crbi